node {
    def myGradleContainer = docker.image('gradle:8.5-jdk8') // Usa Debian, no Alpine
    myGradleContainer.pull()

    stage('Preparación') {
        git branch: 'main', url: 'https://github.com/macloujulian/gs-gradle.git'
    }

    stage('Construcción') {
        myGradleContainer.inside("-v ${env.HOME}/.gradle:/home/gradle/.gradle") {
            sh 'cd complete && gradle build'
        }
    }

    stage('Sonar Scanner') {
        def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
        withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
            sh """
                ${sonarqubeScannerHome}/bin/sonar-scanner \
                -Dsonar.host.url=http://sonarqube:9000 \
                -Dsonar.login=${sonarLogin} \
                -Dsonar.projectName=gs-gradle \
                -Dsonar.projectVersion=${env.BUILD_NUMBER} \
                -Dsonar.projectKey=GS \
                -Dsonar.sources=complete/src/main/ \
                -Dsonar.tests=complete/src/test/ \
                -Dsonar.language=java \
                -Dsonar.java.binaries=complete/build/classes
            """
        }
    }
}
